// Generated by gencpp from file mobiman_msgs/arm_control.msg
// DO NOT EDIT!


#ifndef MOBIMAN_MSGS_MESSAGE_ARM_CONTROL_H
#define MOBIMAN_MSGS_MESSAGE_ARM_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mobiman_msgs
{
template <class ContainerAllocator>
struct arm_control_
{
  typedef arm_control_<ContainerAllocator> Type;

  arm_control_()
    : header()
    , p_des()
    , v_des()
    , kp()
    , kd()
    , t_ff()
    , mode(0)  {
    }
  arm_control_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , p_des(_alloc)
    , v_des(_alloc)
    , kp(_alloc)
    , kd(_alloc)
    , t_ff(_alloc)
    , mode(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _p_des_type;
  _p_des_type p_des;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _v_des_type;
  _v_des_type v_des;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _kp_type;
  _kp_type kp;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _kd_type;
  _kd_type kd;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _t_ff_type;
  _t_ff_type t_ff;

   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::mobiman_msgs::arm_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobiman_msgs::arm_control_<ContainerAllocator> const> ConstPtr;

}; // struct arm_control_

typedef ::mobiman_msgs::arm_control_<std::allocator<void> > arm_control;

typedef boost::shared_ptr< ::mobiman_msgs::arm_control > arm_controlPtr;
typedef boost::shared_ptr< ::mobiman_msgs::arm_control const> arm_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobiman_msgs::arm_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobiman_msgs::arm_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobiman_msgs::arm_control_<ContainerAllocator1> & lhs, const ::mobiman_msgs::arm_control_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.p_des == rhs.p_des &&
    lhs.v_des == rhs.v_des &&
    lhs.kp == rhs.kp &&
    lhs.kd == rhs.kd &&
    lhs.t_ff == rhs.t_ff &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobiman_msgs::arm_control_<ContainerAllocator1> & lhs, const ::mobiman_msgs::arm_control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobiman_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::arm_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::arm_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::arm_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::arm_control_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::arm_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::arm_control_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobiman_msgs::arm_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19f36ff29f95cf7a6da164ce69c0a087";
  }

  static const char* value(const ::mobiman_msgs::arm_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19f36ff29f95cf7aULL;
  static const uint64_t static_value2 = 0x6da164ce69c0a087ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobiman_msgs::arm_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobiman_msgs/arm_control";
  }

  static const char* value(const ::mobiman_msgs::arm_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobiman_msgs::arm_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] p_des\n"
"float32[] v_des\n"
"float32[] kp\n"
"float32[] kd\n"
"float32[] t_ff\n"
"uint8 mode\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mobiman_msgs::arm_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobiman_msgs::arm_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.p_des);
      stream.next(m.v_des);
      stream.next(m.kp);
      stream.next(m.kd);
      stream.next(m.t_ff);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arm_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobiman_msgs::arm_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobiman_msgs::arm_control_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "p_des[]" << std::endl;
    for (size_t i = 0; i < v.p_des.size(); ++i)
    {
      s << indent << "  p_des[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.p_des[i]);
    }
    s << indent << "v_des[]" << std::endl;
    for (size_t i = 0; i < v.v_des.size(); ++i)
    {
      s << indent << "  v_des[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.v_des[i]);
    }
    s << indent << "kp[]" << std::endl;
    for (size_t i = 0; i < v.kp.size(); ++i)
    {
      s << indent << "  kp[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kp[i]);
    }
    s << indent << "kd[]" << std::endl;
    for (size_t i = 0; i < v.kd.size(); ++i)
    {
      s << indent << "  kd[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kd[i]);
    }
    s << indent << "t_ff[]" << std::endl;
    for (size_t i = 0; i < v.t_ff.size(); ++i)
    {
      s << indent << "  t_ff[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.t_ff[i]);
    }
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBIMAN_MSGS_MESSAGE_ARM_CONTROL_H
