// Generated by gencpp from file mobiman_msgs/ArmBasicCommand.msg
// DO NOT EDIT!


#ifndef MOBIMAN_MSGS_MESSAGE_ARMBASICCOMMAND_H
#define MOBIMAN_MSGS_MESSAGE_ARMBASICCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mobiman_msgs/JointPosition.h>
#include <mobiman_msgs/JointSpeed.h>

namespace mobiman_msgs
{
template <class ContainerAllocator>
struct ArmBasicCommand_
{
  typedef ArmBasicCommand_<ContainerAllocator> Type;

  ArmBasicCommand_()
    : header()
    , jpos()
    , jspeed()  {
    }
  ArmBasicCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , jpos(_alloc)
    , jspeed(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::mobiman_msgs::JointPosition_<ContainerAllocator>  _jpos_type;
  _jpos_type jpos;

   typedef  ::mobiman_msgs::JointSpeed_<ContainerAllocator>  _jspeed_type;
  _jspeed_type jspeed;





  typedef boost::shared_ptr< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ArmBasicCommand_

typedef ::mobiman_msgs::ArmBasicCommand_<std::allocator<void> > ArmBasicCommand;

typedef boost::shared_ptr< ::mobiman_msgs::ArmBasicCommand > ArmBasicCommandPtr;
typedef boost::shared_ptr< ::mobiman_msgs::ArmBasicCommand const> ArmBasicCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator1> & lhs, const ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.jpos == rhs.jpos &&
    lhs.jspeed == rhs.jspeed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator1> & lhs, const ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobiman_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcfbc58fb13093c333eea9319796c877";
  }

  static const char* value(const ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcfbc58fb13093c3ULL;
  static const uint64_t static_value2 = 0x33eea9319796c877ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobiman_msgs/ArmBasicCommand";
  }

  static const char* value(const ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"JointPosition jpos\n"
"JointSpeed jspeed\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mobiman_msgs/JointPosition\n"
"float32[] pos\n"
"================================================================================\n"
"MSG: mobiman_msgs/JointSpeed\n"
"float32[] speed\n"
;
  }

  static const char* value(const ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.jpos);
      stream.next(m.jspeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmBasicCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobiman_msgs::ArmBasicCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "jpos: ";
    s << std::endl;
    Printer< ::mobiman_msgs::JointPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.jpos);
    s << indent << "jspeed: ";
    s << std::endl;
    Printer< ::mobiman_msgs::JointSpeed_<ContainerAllocator> >::stream(s, indent + "  ", v.jspeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBIMAN_MSGS_MESSAGE_ARMBASICCOMMAND_H
