// Generated by gencpp from file mobiman_msgs/Button3d.msg
// DO NOT EDIT!


#ifndef MOBIMAN_MSGS_MESSAGE_BUTTON3D_H
#define MOBIMAN_MSGS_MESSAGE_BUTTON3D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <mobiman_msgs/ButtonSemantics.h>

namespace mobiman_msgs
{
template <class ContainerAllocator>
struct Button3d_
{
  typedef Button3d_<ContainerAllocator> Type;

  Button3d_()
    : pose()
    , button_semantics()  {
    }
  Button3d_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , button_semantics(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::mobiman_msgs::ButtonSemantics_<ContainerAllocator>  _button_semantics_type;
  _button_semantics_type button_semantics;





  typedef boost::shared_ptr< ::mobiman_msgs::Button3d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobiman_msgs::Button3d_<ContainerAllocator> const> ConstPtr;

}; // struct Button3d_

typedef ::mobiman_msgs::Button3d_<std::allocator<void> > Button3d;

typedef boost::shared_ptr< ::mobiman_msgs::Button3d > Button3dPtr;
typedef boost::shared_ptr< ::mobiman_msgs::Button3d const> Button3dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobiman_msgs::Button3d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobiman_msgs::Button3d_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobiman_msgs::Button3d_<ContainerAllocator1> & lhs, const ::mobiman_msgs::Button3d_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.button_semantics == rhs.button_semantics;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobiman_msgs::Button3d_<ContainerAllocator1> & lhs, const ::mobiman_msgs::Button3d_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobiman_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::Button3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::Button3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::Button3d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::Button3d_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::Button3d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::Button3d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobiman_msgs::Button3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4cebf7d3838aade9d4cfafbd7ef66592";
  }

  static const char* value(const ::mobiman_msgs::Button3d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4cebf7d3838aade9ULL;
  static const uint64_t static_value2 = 0xd4cfafbd7ef66592ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobiman_msgs::Button3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobiman_msgs/Button3d";
  }

  static const char* value(const ::mobiman_msgs::Button3d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobiman_msgs::Button3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"ButtonSemantics button_semantics\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: mobiman_msgs/ButtonSemantics\n"
"string name\n"
"uint8 button_status\n"
;
  }

  static const char* value(const ::mobiman_msgs::Button3d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobiman_msgs::Button3d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.button_semantics);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Button3d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobiman_msgs::Button3d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobiman_msgs::Button3d_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "button_semantics: ";
    s << std::endl;
    Printer< ::mobiman_msgs::ButtonSemantics_<ContainerAllocator> >::stream(s, indent + "  ", v.button_semantics);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBIMAN_MSGS_MESSAGE_BUTTON3D_H
