// Generated by gencpp from file mobiman_msgs/ChassisCommandStamped.msg
// DO NOT EDIT!


#ifndef MOBIMAN_MSGS_MESSAGE_CHASSISCOMMANDSTAMPED_H
#define MOBIMAN_MSGS_MESSAGE_CHASSISCOMMANDSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mobiman_msgs/ChassisCommand.h>

namespace mobiman_msgs
{
template <class ContainerAllocator>
struct ChassisCommandStamped_
{
  typedef ChassisCommandStamped_<ContainerAllocator> Type;

  ChassisCommandStamped_()
    : header()
    , command()  {
    }
  ChassisCommandStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::mobiman_msgs::ChassisCommand_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> const> ConstPtr;

}; // struct ChassisCommandStamped_

typedef ::mobiman_msgs::ChassisCommandStamped_<std::allocator<void> > ChassisCommandStamped;

typedef boost::shared_ptr< ::mobiman_msgs::ChassisCommandStamped > ChassisCommandStampedPtr;
typedef boost::shared_ptr< ::mobiman_msgs::ChassisCommandStamped const> ChassisCommandStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator1> & lhs, const ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator1> & lhs, const ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobiman_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "123c2e06ca5169bd3a46b31694b50130";
  }

  static const char* value(const ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x123c2e06ca5169bdULL;
  static const uint64_t static_value2 = 0x3a46b31694b50130ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobiman_msgs/ChassisCommandStamped";
  }

  static const char* value(const ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"ChassisCommand command\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mobiman_msgs/ChassisCommand\n"
"# for 4w4s vehicles, the order is [fl, fr, rl ,rr]\n"
"float32[] steer_angles\n"
"float32[] wheel_speed\n"
;
  }

  static const char* value(const ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChassisCommandStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobiman_msgs::ChassisCommandStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "command: ";
    s << std::endl;
    Printer< ::mobiman_msgs::ChassisCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBIMAN_MSGS_MESSAGE_CHASSISCOMMANDSTAMPED_H
