// Generated by gencpp from file mobiman_msgs/JointPositionStamped.msg
// DO NOT EDIT!


#ifndef MOBIMAN_MSGS_MESSAGE_JOINTPOSITIONSTAMPED_H
#define MOBIMAN_MSGS_MESSAGE_JOINTPOSITIONSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mobiman_msgs/JointPosition.h>

namespace mobiman_msgs
{
template <class ContainerAllocator>
struct JointPositionStamped_
{
  typedef JointPositionStamped_<ContainerAllocator> Type;

  JointPositionStamped_()
    : header()
    , pos()  {
    }
  JointPositionStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::mobiman_msgs::JointPosition_<ContainerAllocator>  _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> const> ConstPtr;

}; // struct JointPositionStamped_

typedef ::mobiman_msgs::JointPositionStamped_<std::allocator<void> > JointPositionStamped;

typedef boost::shared_ptr< ::mobiman_msgs::JointPositionStamped > JointPositionStampedPtr;
typedef boost::shared_ptr< ::mobiman_msgs::JointPositionStamped const> JointPositionStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobiman_msgs::JointPositionStamped_<ContainerAllocator1> & lhs, const ::mobiman_msgs::JointPositionStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pos == rhs.pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobiman_msgs::JointPositionStamped_<ContainerAllocator1> & lhs, const ::mobiman_msgs::JointPositionStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobiman_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1eb4f699de878b57462959a77fb2410";
  }

  static const char* value(const ::mobiman_msgs::JointPositionStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1eb4f699de878b5ULL;
  static const uint64_t static_value2 = 0x7462959a77fb2410ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobiman_msgs/JointPositionStamped";
  }

  static const char* value(const ::mobiman_msgs::JointPositionStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"JointPosition pos\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mobiman_msgs/JointPosition\n"
"float32[] pos\n"
;
  }

  static const char* value(const ::mobiman_msgs::JointPositionStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointPositionStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobiman_msgs::JointPositionStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobiman_msgs::JointPositionStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos: ";
    s << std::endl;
    Printer< ::mobiman_msgs::JointPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBIMAN_MSGS_MESSAGE_JOINTPOSITIONSTAMPED_H
