// Generated by gencpp from file mobiman_msgs/Mask.msg
// DO NOT EDIT!


#ifndef MOBIMAN_MSGS_MESSAGE_MASK_H
#define MOBIMAN_MSGS_MESSAGE_MASK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mobiman_msgs
{
template <class ContainerAllocator>
struct Mask_
{
  typedef Mask_<ContainerAllocator> Type;

  Mask_()
    : header()
    , height(0)
    , width(0)
    , data()
    , mask_types()
    , instance_description()  {
    }
  Mask_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , height(0)
    , width(0)
    , data(_alloc)
    , mask_types(_alloc)
    , instance_description(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _height_type;
  _height_type height;

   typedef uint16_t _width_type;
  _width_type width;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _mask_types_type;
  _mask_types_type mask_types;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _instance_description_type;
  _instance_description_type instance_description;





  typedef boost::shared_ptr< ::mobiman_msgs::Mask_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobiman_msgs::Mask_<ContainerAllocator> const> ConstPtr;

}; // struct Mask_

typedef ::mobiman_msgs::Mask_<std::allocator<void> > Mask;

typedef boost::shared_ptr< ::mobiman_msgs::Mask > MaskPtr;
typedef boost::shared_ptr< ::mobiman_msgs::Mask const> MaskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobiman_msgs::Mask_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobiman_msgs::Mask_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobiman_msgs::Mask_<ContainerAllocator1> & lhs, const ::mobiman_msgs::Mask_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.data == rhs.data &&
    lhs.mask_types == rhs.mask_types &&
    lhs.instance_description == rhs.instance_description;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobiman_msgs::Mask_<ContainerAllocator1> & lhs, const ::mobiman_msgs::Mask_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobiman_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::Mask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::Mask_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::Mask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::Mask_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::Mask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::Mask_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobiman_msgs::Mask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a960000413df3e0030443cb5c9082a94";
  }

  static const char* value(const ::mobiman_msgs::Mask_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa960000413df3e00ULL;
  static const uint64_t static_value2 = 0x30443cb5c9082a94ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobiman_msgs::Mask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobiman_msgs/Mask";
  }

  static const char* value(const ::mobiman_msgs::Mask_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobiman_msgs::Mask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint16 height\n"
"uint16 width\n"
"uint8[] data # size h * w, array of mask instance\n"
"uint8[] mask_types # size number of instance\n"
"string[] instance_description # size number of instance\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mobiman_msgs::Mask_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobiman_msgs::Mask_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.data);
      stream.next(m.mask_types);
      stream.next(m.instance_description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mask_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobiman_msgs::Mask_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobiman_msgs::Mask_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "height: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.width);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "mask_types[]" << std::endl;
    for (size_t i = 0; i < v.mask_types.size(); ++i)
    {
      s << indent << "  mask_types[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.mask_types[i]);
    }
    s << indent << "instance_description[]" << std::endl;
    for (size_t i = 0; i < v.instance_description.size(); ++i)
    {
      s << indent << "  instance_description[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.instance_description[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBIMAN_MSGS_MESSAGE_MASK_H
