// Generated by gencpp from file mobiman_msgs/PoseArrayServiceRequest.msg
// DO NOT EDIT!


#ifndef MOBIMAN_MSGS_MESSAGE_POSEARRAYSERVICEREQUEST_H
#define MOBIMAN_MSGS_MESSAGE_POSEARRAYSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace mobiman_msgs
{
template <class ContainerAllocator>
struct PoseArrayServiceRequest_
{
  typedef PoseArrayServiceRequest_<ContainerAllocator> Type;

  PoseArrayServiceRequest_()
    : poses()  {
    }
  PoseArrayServiceRequest_(const ContainerAllocator& _alloc)
    : poses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PoseArrayServiceRequest_

typedef ::mobiman_msgs::PoseArrayServiceRequest_<std::allocator<void> > PoseArrayServiceRequest;

typedef boost::shared_ptr< ::mobiman_msgs::PoseArrayServiceRequest > PoseArrayServiceRequestPtr;
typedef boost::shared_ptr< ::mobiman_msgs::PoseArrayServiceRequest const> PoseArrayServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator1> & lhs, const ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.poses == rhs.poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator1> & lhs, const ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobiman_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "047f8def55b3621b994985089fbb7238";
  }

  static const char* value(const ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x047f8def55b3621bULL;
  static const uint64_t static_value2 = 0x994985089fbb7238ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobiman_msgs/PoseArrayServiceRequest";
  }

  static const char* value(const ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray poses\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseArrayServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobiman_msgs::PoseArrayServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "poses: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.poses);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBIMAN_MSGS_MESSAGE_POSEARRAYSERVICEREQUEST_H
