// Generated by gencpp from file mobiman_msgs/PoseArrayService.msg
// DO NOT EDIT!


#ifndef MOBIMAN_MSGS_MESSAGE_POSEARRAYSERVICE_H
#define MOBIMAN_MSGS_MESSAGE_POSEARRAYSERVICE_H

#include <ros/service_traits.h>


#include <mobiman_msgs/PoseArrayServiceRequest.h>
#include <mobiman_msgs/PoseArrayServiceResponse.h>


namespace mobiman_msgs
{

struct PoseArrayService
{

typedef PoseArrayServiceRequest Request;
typedef PoseArrayServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseArrayService
} // namespace mobiman_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mobiman_msgs::PoseArrayService > {
  static const char* value()
  {
    return "248320f22709534d9c1f1e28f3b6fa63";
  }

  static const char* value(const ::mobiman_msgs::PoseArrayService&) { return value(); }
};

template<>
struct DataType< ::mobiman_msgs::PoseArrayService > {
  static const char* value()
  {
    return "mobiman_msgs/PoseArrayService";
  }

  static const char* value(const ::mobiman_msgs::PoseArrayService&) { return value(); }
};


// service_traits::MD5Sum< ::mobiman_msgs::PoseArrayServiceRequest> should match
// service_traits::MD5Sum< ::mobiman_msgs::PoseArrayService >
template<>
struct MD5Sum< ::mobiman_msgs::PoseArrayServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mobiman_msgs::PoseArrayService >::value();
  }
  static const char* value(const ::mobiman_msgs::PoseArrayServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobiman_msgs::PoseArrayServiceRequest> should match
// service_traits::DataType< ::mobiman_msgs::PoseArrayService >
template<>
struct DataType< ::mobiman_msgs::PoseArrayServiceRequest>
{
  static const char* value()
  {
    return DataType< ::mobiman_msgs::PoseArrayService >::value();
  }
  static const char* value(const ::mobiman_msgs::PoseArrayServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mobiman_msgs::PoseArrayServiceResponse> should match
// service_traits::MD5Sum< ::mobiman_msgs::PoseArrayService >
template<>
struct MD5Sum< ::mobiman_msgs::PoseArrayServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mobiman_msgs::PoseArrayService >::value();
  }
  static const char* value(const ::mobiman_msgs::PoseArrayServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobiman_msgs::PoseArrayServiceResponse> should match
// service_traits::DataType< ::mobiman_msgs::PoseArrayService >
template<>
struct DataType< ::mobiman_msgs::PoseArrayServiceResponse>
{
  static const char* value()
  {
    return DataType< ::mobiman_msgs::PoseArrayService >::value();
  }
  static const char* value(const ::mobiman_msgs::PoseArrayServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOBIMAN_MSGS_MESSAGE_POSEARRAYSERVICE_H
