// Generated by gencpp from file mobiman_msgs/PoseArrayServiceResponse.msg
// DO NOT EDIT!


#ifndef MOBIMAN_MSGS_MESSAGE_POSEARRAYSERVICERESPONSE_H
#define MOBIMAN_MSGS_MESSAGE_POSEARRAYSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobiman_msgs
{
template <class ContainerAllocator>
struct PoseArrayServiceResponse_
{
  typedef PoseArrayServiceResponse_<ContainerAllocator> Type;

  PoseArrayServiceResponse_()
    : success(false)  {
    }
  PoseArrayServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PoseArrayServiceResponse_

typedef ::mobiman_msgs::PoseArrayServiceResponse_<std::allocator<void> > PoseArrayServiceResponse;

typedef boost::shared_ptr< ::mobiman_msgs::PoseArrayServiceResponse > PoseArrayServiceResponsePtr;
typedef boost::shared_ptr< ::mobiman_msgs::PoseArrayServiceResponse const> PoseArrayServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator1> & lhs, const ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator1> & lhs, const ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobiman_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobiman_msgs/PoseArrayServiceResponse";
  }

  static const char* value(const ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
"\n"
;
  }

  static const char* value(const ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseArrayServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobiman_msgs::PoseArrayServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBIMAN_MSGS_MESSAGE_POSEARRAYSERVICERESPONSE_H
