# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from signal_chassis/Drivetrain_r1.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Drivetrain_r1(genpy.Message):
  _md5sum = "d64ee0e637d15c359801b97bc246779d"
  _type = "signal_chassis/Drivetrain_r1"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 steer_angle_front_left
float32 steer_angle_front_right
float32 steer_angle_rear
float32 drive_speed_front_left
float32 drive_speed_front_right
float32 drive_speed_rear
float32 drive_angular_speed_front_left
float32 drive_angular_speed_front_right
float32 drive_angular_speed_rear"""
  __slots__ = ['steer_angle_front_left','steer_angle_front_right','steer_angle_rear','drive_speed_front_left','drive_speed_front_right','drive_speed_rear','drive_angular_speed_front_left','drive_angular_speed_front_right','drive_angular_speed_rear']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       steer_angle_front_left,steer_angle_front_right,steer_angle_rear,drive_speed_front_left,drive_speed_front_right,drive_speed_rear,drive_angular_speed_front_left,drive_angular_speed_front_right,drive_angular_speed_rear

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Drivetrain_r1, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.steer_angle_front_left is None:
        self.steer_angle_front_left = 0.
      if self.steer_angle_front_right is None:
        self.steer_angle_front_right = 0.
      if self.steer_angle_rear is None:
        self.steer_angle_rear = 0.
      if self.drive_speed_front_left is None:
        self.drive_speed_front_left = 0.
      if self.drive_speed_front_right is None:
        self.drive_speed_front_right = 0.
      if self.drive_speed_rear is None:
        self.drive_speed_rear = 0.
      if self.drive_angular_speed_front_left is None:
        self.drive_angular_speed_front_left = 0.
      if self.drive_angular_speed_front_right is None:
        self.drive_angular_speed_front_right = 0.
      if self.drive_angular_speed_rear is None:
        self.drive_angular_speed_rear = 0.
    else:
      self.steer_angle_front_left = 0.
      self.steer_angle_front_right = 0.
      self.steer_angle_rear = 0.
      self.drive_speed_front_left = 0.
      self.drive_speed_front_right = 0.
      self.drive_speed_rear = 0.
      self.drive_angular_speed_front_left = 0.
      self.drive_angular_speed_front_right = 0.
      self.drive_angular_speed_rear = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.steer_angle_front_left, _x.steer_angle_front_right, _x.steer_angle_rear, _x.drive_speed_front_left, _x.drive_speed_front_right, _x.drive_speed_rear, _x.drive_angular_speed_front_left, _x.drive_angular_speed_front_right, _x.drive_angular_speed_rear))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.steer_angle_front_left, _x.steer_angle_front_right, _x.steer_angle_rear, _x.drive_speed_front_left, _x.drive_speed_front_right, _x.drive_speed_rear, _x.drive_angular_speed_front_left, _x.drive_angular_speed_front_right, _x.drive_angular_speed_rear,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.steer_angle_front_left, _x.steer_angle_front_right, _x.steer_angle_rear, _x.drive_speed_front_left, _x.drive_speed_front_right, _x.drive_speed_rear, _x.drive_angular_speed_front_left, _x.drive_angular_speed_front_right, _x.drive_angular_speed_rear))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.steer_angle_front_left, _x.steer_angle_front_right, _x.steer_angle_rear, _x.drive_speed_front_left, _x.drive_speed_front_right, _x.drive_speed_rear, _x.drive_angular_speed_front_left, _x.drive_angular_speed_front_right, _x.drive_angular_speed_rear,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9f = None
def _get_struct_9f():
    global _struct_9f
    if _struct_9f is None:
        _struct_9f = struct.Struct("<9f")
    return _struct_9f
