# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ocs2_msgs/mpc_performance_indices.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class mpc_performance_indices(genpy.Message):
  _md5sum = "d3efdce4c946e170e65e642157f48398"
  _type = "ocs2_msgs/mpc_performance_indices"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# MPC performance indices
float32     initTime
float32     merit
float32     cost
float32     dynamicsViolationSSE
float32     equalityConstraintsSSE
float32     equalityLagrangian
float32     inequalityLagrangian
"""
  __slots__ = ['initTime','merit','cost','dynamicsViolationSSE','equalityConstraintsSSE','equalityLagrangian','inequalityLagrangian']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       initTime,merit,cost,dynamicsViolationSSE,equalityConstraintsSSE,equalityLagrangian,inequalityLagrangian

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mpc_performance_indices, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.initTime is None:
        self.initTime = 0.
      if self.merit is None:
        self.merit = 0.
      if self.cost is None:
        self.cost = 0.
      if self.dynamicsViolationSSE is None:
        self.dynamicsViolationSSE = 0.
      if self.equalityConstraintsSSE is None:
        self.equalityConstraintsSSE = 0.
      if self.equalityLagrangian is None:
        self.equalityLagrangian = 0.
      if self.inequalityLagrangian is None:
        self.inequalityLagrangian = 0.
    else:
      self.initTime = 0.
      self.merit = 0.
      self.cost = 0.
      self.dynamicsViolationSSE = 0.
      self.equalityConstraintsSSE = 0.
      self.equalityLagrangian = 0.
      self.inequalityLagrangian = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.initTime, _x.merit, _x.cost, _x.dynamicsViolationSSE, _x.equalityConstraintsSSE, _x.equalityLagrangian, _x.inequalityLagrangian))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.initTime, _x.merit, _x.cost, _x.dynamicsViolationSSE, _x.equalityConstraintsSSE, _x.equalityLagrangian, _x.inequalityLagrangian,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.initTime, _x.merit, _x.cost, _x.dynamicsViolationSSE, _x.equalityConstraintsSSE, _x.equalityLagrangian, _x.inequalityLagrangian))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.initTime, _x.merit, _x.cost, _x.dynamicsViolationSSE, _x.equalityConstraintsSSE, _x.equalityLagrangian, _x.inequalityLagrangian,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
