(cl:in-package signal_chassis-msg)
(cl:export '(STEER_ANGLE_FRONT_LEFT-VAL
          STEER_ANGLE_FRONT_LEFT
          STEER_ANGLE_FRONT_RIGHT-VAL
          STEER_ANGLE_FRONT_RIGHT
          STEER_ANGLE_REAR-VAL
          STEER_ANGLE_REAR
          DRIVE_SPEED_FRONT_LEFT-VAL
          DRIVE_SPEED_FRONT_LEFT
          DRIVE_SPEED_FRONT_RIGHT-VAL
          DRIVE_SPEED_FRONT_RIGHT
          DRIVE_SPEED_REAR-VAL
          DRIVE_SPEED_REAR
          DRIVE_ANGULAR_SPEED_FRONT_LEFT-VAL
          DRIVE_ANGULAR_SPEED_FRONT_LEFT
          DRIVE_ANGULAR_SPEED_FRONT_RIGHT-VAL
          DRIVE_ANGULAR_SPEED_FRONT_RIGHT
          DRIVE_ANGULAR_SPEED_REAR-VAL
          DRIVE_ANGULAR_SPEED_REAR
))