(cl:in-package signal_chassis-msg)
(cl:export '(STEER_ANGLE_FL-VAL
          STEER_ANGLE_FL
          STEER_ANGLE_FR-VAL
          STEER_ANGLE_FR
          STEER_ANGLE_RL-VAL
          STEER_ANGLE_RL
          STEER_ANGLE_RR-VAL
          STEER_ANGLE_RR
          DRIVE_SPEED_FL-VAL
          DRIVE_SPEED_FL
          DRIVE_SPEED_FR-VAL
          DRIVE_SPEED_FR
          DRIVE_SPEED_RL-VAL
          DRIVE_SPEED_RL
          DRIVE_SPEED_RR-VAL
          DRIVE_SPEED_RR
          DRIVE_ANGULAR_SPEED_FL-VAL
          DRIVE_ANGULAR_SPEED_FL
          DRIVE_ANGULAR_SPEED_FR-VAL
          DRIVE_ANGULAR_SPEED_FR
          DRIVE_ANGULAR_SPEED_RL-VAL
          DRIVE_ANGULAR_SPEED_RL
          DRIVE_ANGULAR_SPEED_RR-VAL
          DRIVE_ANGULAR_SPEED_RR
          MOTION_MODE-VAL
          MOTION_MODE
))