// Generated by gencpp from file signal_torso/FunctionFrameResponse.msg
// DO NOT EDIT!


#ifndef SIGNAL_TORSO_MESSAGE_FUNCTIONFRAMERESPONSE_H
#define SIGNAL_TORSO_MESSAGE_FUNCTIONFRAMERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace signal_torso
{
template <class ContainerAllocator>
struct FunctionFrameResponse_
{
  typedef FunctionFrameResponse_<ContainerAllocator> Type;

  FunctionFrameResponse_()
    : success(false)
    , message()  {
    }
  FunctionFrameResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FunctionFrameResponse_

typedef ::signal_torso::FunctionFrameResponse_<std::allocator<void> > FunctionFrameResponse;

typedef boost::shared_ptr< ::signal_torso::FunctionFrameResponse > FunctionFrameResponsePtr;
typedef boost::shared_ptr< ::signal_torso::FunctionFrameResponse const> FunctionFrameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::signal_torso::FunctionFrameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::signal_torso::FunctionFrameResponse_<ContainerAllocator1> & lhs, const ::signal_torso::FunctionFrameResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::signal_torso::FunctionFrameResponse_<ContainerAllocator1> & lhs, const ::signal_torso::FunctionFrameResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace signal_torso

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::signal_torso::FunctionFrameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "signal_torso/FunctionFrameResponse";
  }

  static const char* value(const ::signal_torso::FunctionFrameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::signal_torso::FunctionFrameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FunctionFrameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::signal_torso::FunctionFrameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::signal_torso::FunctionFrameResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIGNAL_TORSO_MESSAGE_FUNCTIONFRAMERESPONSE_H
