// Generated by gencpp from file signal_torso/torso_status.msg
// DO NOT EDIT!


#ifndef SIGNAL_TORSO_MESSAGE_TORSO_STATUS_H
#define SIGNAL_TORSO_MESSAGE_TORSO_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace signal_torso
{
template <class ContainerAllocator>
struct torso_status_
{
  typedef torso_status_<ContainerAllocator> Type;

  torso_status_()
    : name()
    , motor_temperature()
    , braking_state()
    , motor_voltage()
    , error_code()  {
    }
  torso_status_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , motor_temperature(_alloc)
    , braking_state(_alloc)
    , motor_voltage(_alloc)
    , error_code(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _motor_temperature_type;
  _motor_temperature_type motor_temperature;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _braking_state_type;
  _braking_state_type braking_state;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _motor_voltage_type;
  _motor_voltage_type motor_voltage;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::signal_torso::torso_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::signal_torso::torso_status_<ContainerAllocator> const> ConstPtr;

}; // struct torso_status_

typedef ::signal_torso::torso_status_<std::allocator<void> > torso_status;

typedef boost::shared_ptr< ::signal_torso::torso_status > torso_statusPtr;
typedef boost::shared_ptr< ::signal_torso::torso_status const> torso_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::signal_torso::torso_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::signal_torso::torso_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::signal_torso::torso_status_<ContainerAllocator1> & lhs, const ::signal_torso::torso_status_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.motor_temperature == rhs.motor_temperature &&
    lhs.braking_state == rhs.braking_state &&
    lhs.motor_voltage == rhs.motor_voltage &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::signal_torso::torso_status_<ContainerAllocator1> & lhs, const ::signal_torso::torso_status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace signal_torso

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::signal_torso::torso_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::signal_torso::torso_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_torso::torso_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_torso::torso_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_torso::torso_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_torso::torso_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::signal_torso::torso_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3302cf44c7333c5f9df707eac2f97f07";
  }

  static const char* value(const ::signal_torso::torso_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3302cf44c7333c5fULL;
  static const uint64_t static_value2 = 0x9df707eac2f97f07ULL;
};

template<class ContainerAllocator>
struct DataType< ::signal_torso::torso_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "signal_torso/torso_status";
  }

  static const char* value(const ::signal_torso::torso_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::signal_torso::torso_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name\n"
"uint8[] motor_temperature\n"
"uint8[] braking_state\n"
"uint16[] motor_voltage\n"
"uint16[] error_code\n"
;
  }

  static const char* value(const ::signal_torso::torso_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::signal_torso::torso_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.motor_temperature);
      stream.next(m.braking_state);
      stream.next(m.motor_voltage);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct torso_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::signal_torso::torso_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::signal_torso::torso_status_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "motor_temperature[]" << std::endl;
    for (size_t i = 0; i < v.motor_temperature.size(); ++i)
    {
      s << indent << "  motor_temperature[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.motor_temperature[i]);
    }
    s << indent << "braking_state[]" << std::endl;
    for (size_t i = 0; i < v.braking_state.size(); ++i)
    {
      s << indent << "  braking_state[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.braking_state[i]);
    }
    s << indent << "motor_voltage[]" << std::endl;
    for (size_t i = 0; i < v.motor_voltage.size(); ++i)
    {
      s << indent << "  motor_voltage[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.motor_voltage[i]);
    }
    s << indent << "error_code[]" << std::endl;
    for (size_t i = 0; i < v.error_code.size(); ++i)
    {
      s << indent << "  error_code[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.error_code[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIGNAL_TORSO_MESSAGE_TORSO_STATUS_H
