(cl:defpackage signal_arm-msg
  (:use )
  (:export
   "<ARM_CONTROL>"
   "ARM_CONTROL"
   "<CONTROL>"
   "CONTROL"
   "<CONTROL_STAMPED>"
   "CONTROL_STAMPED"
   "<GRIPPER_JOINT_COMMAND>"
   "GRIPPER_JOINT_COMMAND"
   "<GRIPPER_POSITION_CONTROL>"
   "GRIPPER_POSITION_CONTROL"
   "<MOTOR_ERROR>"
   "MOTOR_ERROR"
   "<STATUS>"
   "STATUS"
   "<STATUS_STAMPED>"
   "STATUS_STAMPED"
  ))

