(cl:in-package ocs2_msgs-msg)
(cl:export '(CONTROLLERTYPE-VAL
          CONTROLLERTYPE
          INITOBSERVATION-VAL
          INITOBSERVATION
          PLANTARGETTRAJECTORIES-VAL
          PLANTARGETTRAJECTORIES
          STATETRAJECTORY-VAL
          STATETRAJECTORY
          INPUTTRAJECTORY-VAL
          INPUTTRAJECTORY
          TIMETRAJECTORY-VAL
          TIMETRAJECTORY
          POSTEVENTINDICES-VAL
          POSTEVENTINDICES
          MODESCHEDULE-VAL
          MODESCHEDULE
          DATA-VAL
          DATA
          PERFORMANCEINDICES-VAL
          PERFORMANCEINDICES
))