(cl:defpackage signal_torso-msg
  (:use )
  (:export
   "<ARM_CONTROL>"
   "ARM_CONTROL"
   "<STATUS>"
   "STATUS"
   "<STATUS_STAMPED>"
   "STATUS_STAMPED"
   "<TORSO_CONTROL>"
   "TORSO_CONTROL"
   "<TORSO_CONTROL_STAMPED>"
   "TORSO_CONTROL_STAMPED"
   "<TORSO_STATUS>"
   "TORSO_STATUS"
   "<TORSO_STATUS_STAMPED>"
   "TORSO_STATUS_STAMPED"
  ))

