; Auto-generated. Do not edit!


(cl:in-package signal_torso-msg)


;//! \htmlinclude torso_control.msg.html

(cl:defclass <torso_control> (roslisp-msg-protocol:ros-message)
  ((position_des
    :reader position_des
    :initarg :position_des
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (speed_des
    :reader speed_des
    :initarg :speed_des
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (current_kp
    :reader current_kp
    :initarg :current_kp
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (current_kd
    :reader current_kd
    :initarg :current_kd
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (speed_kp
    :reader speed_kp
    :initarg :speed_kp
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (speed_kd
    :reader speed_kd
    :initarg :speed_kd
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (position_kp
    :reader position_kp
    :initarg :position_kp
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (position_kd
    :reader position_kd
    :initarg :position_kd
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0)))
)

(cl:defclass torso_control (<torso_control>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <torso_control>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'torso_control)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name signal_torso-msg:<torso_control> is deprecated: use signal_torso-msg:torso_control instead.")))

(cl:ensure-generic-function 'position_des-val :lambda-list '(m))
(cl:defmethod position_des-val ((m <torso_control>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader signal_torso-msg:position_des-val is deprecated.  Use signal_torso-msg:position_des instead.")
  (position_des m))

(cl:ensure-generic-function 'speed_des-val :lambda-list '(m))
(cl:defmethod speed_des-val ((m <torso_control>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader signal_torso-msg:speed_des-val is deprecated.  Use signal_torso-msg:speed_des instead.")
  (speed_des m))

(cl:ensure-generic-function 'current_kp-val :lambda-list '(m))
(cl:defmethod current_kp-val ((m <torso_control>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader signal_torso-msg:current_kp-val is deprecated.  Use signal_torso-msg:current_kp instead.")
  (current_kp m))

(cl:ensure-generic-function 'current_kd-val :lambda-list '(m))
(cl:defmethod current_kd-val ((m <torso_control>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader signal_torso-msg:current_kd-val is deprecated.  Use signal_torso-msg:current_kd instead.")
  (current_kd m))

(cl:ensure-generic-function 'speed_kp-val :lambda-list '(m))
(cl:defmethod speed_kp-val ((m <torso_control>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader signal_torso-msg:speed_kp-val is deprecated.  Use signal_torso-msg:speed_kp instead.")
  (speed_kp m))

(cl:ensure-generic-function 'speed_kd-val :lambda-list '(m))
(cl:defmethod speed_kd-val ((m <torso_control>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader signal_torso-msg:speed_kd-val is deprecated.  Use signal_torso-msg:speed_kd instead.")
  (speed_kd m))

(cl:ensure-generic-function 'position_kp-val :lambda-list '(m))
(cl:defmethod position_kp-val ((m <torso_control>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader signal_torso-msg:position_kp-val is deprecated.  Use signal_torso-msg:position_kp instead.")
  (position_kp m))

(cl:ensure-generic-function 'position_kd-val :lambda-list '(m))
(cl:defmethod position_kd-val ((m <torso_control>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader signal_torso-msg:position_kd-val is deprecated.  Use signal_torso-msg:position_kd instead.")
  (position_kd m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <torso_control>) ostream)
  "Serializes a message object of type '<torso_control>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'position_des))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'position_des))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'speed_des))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'speed_des))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'current_kp))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream))
   (cl:slot-value msg 'current_kp))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'current_kd))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream))
   (cl:slot-value msg 'current_kd))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'speed_kp))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream))
   (cl:slot-value msg 'speed_kp))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'speed_kd))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream))
   (cl:slot-value msg 'speed_kd))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'position_kp))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream))
   (cl:slot-value msg 'position_kp))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'position_kd))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream))
   (cl:slot-value msg 'position_kd))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <torso_control>) istream)
  "Deserializes a message object of type '<torso_control>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'position_des) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'position_des)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'speed_des) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'speed_des)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'current_kp) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'current_kp)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'current_kd) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'current_kd)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'speed_kp) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'speed_kp)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'speed_kd) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'speed_kd)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'position_kp) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'position_kp)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'position_kd) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'position_kd)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<torso_control>)))
  "Returns string type for a message object of type '<torso_control>"
  "signal_torso/torso_control")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'torso_control)))
  "Returns string type for a message object of type 'torso_control"
  "signal_torso/torso_control")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<torso_control>)))
  "Returns md5sum for a message object of type '<torso_control>"
  "1ef265c20ffbd4e92c2ffec96f296f0c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'torso_control)))
  "Returns md5sum for a message object of type 'torso_control"
  "1ef265c20ffbd4e92c2ffec96f296f0c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<torso_control>)))
  "Returns full string definition for message of type '<torso_control>"
  (cl:format cl:nil "float32[] position_des~%float32[] speed_des~%uint8[] current_kp~%uint8[] current_kd~%uint8[] speed_kp~%uint8[] speed_kd~%uint8[] position_kp~%uint8[] position_kd~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'torso_control)))
  "Returns full string definition for message of type 'torso_control"
  (cl:format cl:nil "float32[] position_des~%float32[] speed_des~%uint8[] current_kp~%uint8[] current_kd~%uint8[] speed_kp~%uint8[] speed_kd~%uint8[] position_kp~%uint8[] position_kd~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <torso_control>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'position_des) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'speed_des) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'current_kp) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'current_kd) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'speed_kp) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'speed_kd) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'position_kp) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'position_kd) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <torso_control>))
  "Converts a ROS message object to a list"
  (cl:list 'torso_control
    (cl:cons ':position_des (position_des msg))
    (cl:cons ':speed_des (speed_des msg))
    (cl:cons ':current_kp (current_kp msg))
    (cl:cons ':current_kd (current_kd msg))
    (cl:cons ':speed_kp (speed_kp msg))
    (cl:cons ':speed_kd (speed_kd msg))
    (cl:cons ':position_kp (position_kp msg))
    (cl:cons ':position_kd (position_kd msg))
))
