(cl:defpackage mobiman_msgs-srv
  (:use )
  (:export
   "POSEARRAYSERVICE"
   "<POSEARRAYSERVICE-REQUEST>"
   "POSEARRAYSERVICE-REQUEST"
   "<POSEARRAYSERVICE-RESPONSE>"
   "POSEARRAYSERVICE-RESPONSE"
  ))

