(cl:defpackage mobiman_msgs-srv
  (:use )
  (:export
   "IKSERVICE"
   "<IKSERVICE-REQUEST>"
   "IKSERVICE-REQUEST"
   "<IKSERVICE-RESPONSE>"
   "IKSERVICE-RESPONSE"
   "POSEARRAYSERVICE"
   "<POSEARRAYSERVICE-REQUEST>"
   "POSEARRAYSERVICE-REQUEST"
   "<POSEARRAYSERVICE-RESPONSE>"
   "POSEARRAYSERVICE-RESPONSE"
  ))

