// Generated by gencpp from file ocs2_msgs/constraint.msg
// DO NOT EDIT!


#ifndef OCS2_MSGS_MESSAGE_CONSTRAINT_H
#define OCS2_MSGS_MESSAGE_CONSTRAINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ocs2_msgs
{
template <class ContainerAllocator>
struct constraint_
{
  typedef constraint_<ContainerAllocator> Type;

  constraint_()
    : time(0.0)
    , value()  {
    }
  constraint_(const ContainerAllocator& _alloc)
    : time(0.0)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef float _time_type;
  _time_type time;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::ocs2_msgs::constraint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ocs2_msgs::constraint_<ContainerAllocator> const> ConstPtr;

}; // struct constraint_

typedef ::ocs2_msgs::constraint_<std::allocator<void> > constraint;

typedef boost::shared_ptr< ::ocs2_msgs::constraint > constraintPtr;
typedef boost::shared_ptr< ::ocs2_msgs::constraint const> constraintConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ocs2_msgs::constraint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ocs2_msgs::constraint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ocs2_msgs::constraint_<ContainerAllocator1> & lhs, const ::ocs2_msgs::constraint_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ocs2_msgs::constraint_<ContainerAllocator1> & lhs, const ::ocs2_msgs::constraint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ocs2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ocs2_msgs::constraint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ocs2_msgs::constraint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ocs2_msgs::constraint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ocs2_msgs::constraint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ocs2_msgs::constraint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ocs2_msgs::constraint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ocs2_msgs::constraint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbeb4e9009e109d77fd87752ca8b68c4";
  }

  static const char* value(const ::ocs2_msgs::constraint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbeb4e9009e109d7ULL;
  static const uint64_t static_value2 = 0x7fd87752ca8b68c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ocs2_msgs::constraint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ocs2_msgs/constraint";
  }

  static const char* value(const ::ocs2_msgs::constraint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ocs2_msgs::constraint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# MPC constraint\n"
"\n"
"float32   time\n"
"float32[] value\n"
;
  }

  static const char* value(const ::ocs2_msgs::constraint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ocs2_msgs::constraint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct constraint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ocs2_msgs::constraint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ocs2_msgs::constraint_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OCS2_MSGS_MESSAGE_CONSTRAINT_H
