// Generated by gencpp from file ocs2_msgs/multiplier.msg
// DO NOT EDIT!


#ifndef OCS2_MSGS_MESSAGE_MULTIPLIER_H
#define OCS2_MSGS_MESSAGE_MULTIPLIER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ocs2_msgs
{
template <class ContainerAllocator>
struct multiplier_
{
  typedef multiplier_<ContainerAllocator> Type;

  multiplier_()
    : time(0.0)
    , penalty(0.0)
    , lagrangian()  {
    }
  multiplier_(const ContainerAllocator& _alloc)
    : time(0.0)
    , penalty(0.0)
    , lagrangian(_alloc)  {
  (void)_alloc;
    }



   typedef float _time_type;
  _time_type time;

   typedef float _penalty_type;
  _penalty_type penalty;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _lagrangian_type;
  _lagrangian_type lagrangian;





  typedef boost::shared_ptr< ::ocs2_msgs::multiplier_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ocs2_msgs::multiplier_<ContainerAllocator> const> ConstPtr;

}; // struct multiplier_

typedef ::ocs2_msgs::multiplier_<std::allocator<void> > multiplier;

typedef boost::shared_ptr< ::ocs2_msgs::multiplier > multiplierPtr;
typedef boost::shared_ptr< ::ocs2_msgs::multiplier const> multiplierConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ocs2_msgs::multiplier_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ocs2_msgs::multiplier_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ocs2_msgs::multiplier_<ContainerAllocator1> & lhs, const ::ocs2_msgs::multiplier_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.penalty == rhs.penalty &&
    lhs.lagrangian == rhs.lagrangian;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ocs2_msgs::multiplier_<ContainerAllocator1> & lhs, const ::ocs2_msgs::multiplier_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ocs2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ocs2_msgs::multiplier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ocs2_msgs::multiplier_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ocs2_msgs::multiplier_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ocs2_msgs::multiplier_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ocs2_msgs::multiplier_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ocs2_msgs::multiplier_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ocs2_msgs::multiplier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8284394e15f2038e54705abd91aee001";
  }

  static const char* value(const ::ocs2_msgs::multiplier_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8284394e15f2038eULL;
  static const uint64_t static_value2 = 0x54705abd91aee001ULL;
};

template<class ContainerAllocator>
struct DataType< ::ocs2_msgs::multiplier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ocs2_msgs/multiplier";
  }

  static const char* value(const ::ocs2_msgs::multiplier_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ocs2_msgs::multiplier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# MPC multiplier\n"
"\n"
"float32   time\n"
"float32   penalty\n"
"float32[] lagrangian\n"
;
  }

  static const char* value(const ::ocs2_msgs::multiplier_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ocs2_msgs::multiplier_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.penalty);
      stream.next(m.lagrangian);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multiplier_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ocs2_msgs::multiplier_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ocs2_msgs::multiplier_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
    s << indent << "penalty: ";
    Printer<float>::stream(s, indent + "  ", v.penalty);
    s << indent << "lagrangian[]" << std::endl;
    for (size_t i = 0; i < v.lagrangian.size(); ++i)
    {
      s << indent << "  lagrangian[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.lagrangian[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OCS2_MSGS_MESSAGE_MULTIPLIER_H
