// Generated by gencpp from file ocs2_msgs/reset.msg
// DO NOT EDIT!


#ifndef OCS2_MSGS_MESSAGE_RESET_H
#define OCS2_MSGS_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <ocs2_msgs/resetRequest.h>
#include <ocs2_msgs/resetResponse.h>


namespace ocs2_msgs
{

struct reset
{

typedef resetRequest Request;
typedef resetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset
} // namespace ocs2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ocs2_msgs::reset > {
  static const char* value()
  {
    return "5d381de3cef01856decae8f3f4a35b69";
  }

  static const char* value(const ::ocs2_msgs::reset&) { return value(); }
};

template<>
struct DataType< ::ocs2_msgs::reset > {
  static const char* value()
  {
    return "ocs2_msgs/reset";
  }

  static const char* value(const ::ocs2_msgs::reset&) { return value(); }
};


// service_traits::MD5Sum< ::ocs2_msgs::resetRequest> should match
// service_traits::MD5Sum< ::ocs2_msgs::reset >
template<>
struct MD5Sum< ::ocs2_msgs::resetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ocs2_msgs::reset >::value();
  }
  static const char* value(const ::ocs2_msgs::resetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ocs2_msgs::resetRequest> should match
// service_traits::DataType< ::ocs2_msgs::reset >
template<>
struct DataType< ::ocs2_msgs::resetRequest>
{
  static const char* value()
  {
    return DataType< ::ocs2_msgs::reset >::value();
  }
  static const char* value(const ::ocs2_msgs::resetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ocs2_msgs::resetResponse> should match
// service_traits::MD5Sum< ::ocs2_msgs::reset >
template<>
struct MD5Sum< ::ocs2_msgs::resetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ocs2_msgs::reset >::value();
  }
  static const char* value(const ::ocs2_msgs::resetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ocs2_msgs::resetResponse> should match
// service_traits::DataType< ::ocs2_msgs::reset >
template<>
struct DataType< ::ocs2_msgs::resetResponse>
{
  static const char* value()
  {
    return DataType< ::ocs2_msgs::reset >::value();
  }
  static const char* value(const ::ocs2_msgs::resetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OCS2_MSGS_MESSAGE_RESET_H
