// Generated by gencpp from file signal_arm/FunctionFrameRequest.msg
// DO NOT EDIT!


#ifndef SIGNAL_ARM_MESSAGE_FUNCTIONFRAMEREQUEST_H
#define SIGNAL_ARM_MESSAGE_FUNCTIONFRAMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace signal_arm
{
template <class ContainerAllocator>
struct FunctionFrameRequest_
{
  typedef FunctionFrameRequest_<ContainerAllocator> Type;

  FunctionFrameRequest_()
    : command(0)  {
    }
  FunctionFrameRequest_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FunctionFrameRequest_

typedef ::signal_arm::FunctionFrameRequest_<std::allocator<void> > FunctionFrameRequest;

typedef boost::shared_ptr< ::signal_arm::FunctionFrameRequest > FunctionFrameRequestPtr;
typedef boost::shared_ptr< ::signal_arm::FunctionFrameRequest const> FunctionFrameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::signal_arm::FunctionFrameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::signal_arm::FunctionFrameRequest_<ContainerAllocator1> & lhs, const ::signal_arm::FunctionFrameRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::signal_arm::FunctionFrameRequest_<ContainerAllocator1> & lhs, const ::signal_arm::FunctionFrameRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace signal_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36e1d21d1340e2a5e93f075b6457cbdf";
  }

  static const char* value(const ::signal_arm::FunctionFrameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36e1d21d1340e2a5ULL;
  static const uint64_t static_value2 = 0xe93f075b6457cbdfULL;
};

template<class ContainerAllocator>
struct DataType< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "signal_arm/FunctionFrameRequest";
  }

  static const char* value(const ::signal_arm::FunctionFrameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 command\n"
;
  }

  static const char* value(const ::signal_arm::FunctionFrameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FunctionFrameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::signal_arm::FunctionFrameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::signal_arm::FunctionFrameRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIGNAL_ARM_MESSAGE_FUNCTIONFRAMEREQUEST_H
