// Generated by gencpp from file signal_arm/gripper_joint_command.msg
// DO NOT EDIT!


#ifndef SIGNAL_ARM_MESSAGE_GRIPPER_JOINT_COMMAND_H
#define SIGNAL_ARM_MESSAGE_GRIPPER_JOINT_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace signal_arm
{
template <class ContainerAllocator>
struct gripper_joint_command_
{
  typedef gripper_joint_command_<ContainerAllocator> Type;

  gripper_joint_command_()
    : header()
    , gripper_force(0.0)  {
    }
  gripper_joint_command_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gripper_force(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _gripper_force_type;
  _gripper_force_type gripper_force;





  typedef boost::shared_ptr< ::signal_arm::gripper_joint_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::signal_arm::gripper_joint_command_<ContainerAllocator> const> ConstPtr;

}; // struct gripper_joint_command_

typedef ::signal_arm::gripper_joint_command_<std::allocator<void> > gripper_joint_command;

typedef boost::shared_ptr< ::signal_arm::gripper_joint_command > gripper_joint_commandPtr;
typedef boost::shared_ptr< ::signal_arm::gripper_joint_command const> gripper_joint_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::signal_arm::gripper_joint_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::signal_arm::gripper_joint_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::signal_arm::gripper_joint_command_<ContainerAllocator1> & lhs, const ::signal_arm::gripper_joint_command_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gripper_force == rhs.gripper_force;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::signal_arm::gripper_joint_command_<ContainerAllocator1> & lhs, const ::signal_arm::gripper_joint_command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace signal_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::signal_arm::gripper_joint_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::signal_arm::gripper_joint_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_arm::gripper_joint_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_arm::gripper_joint_command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_arm::gripper_joint_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_arm::gripper_joint_command_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::signal_arm::gripper_joint_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19416ab4f14f2a0774e2bcefcc994034";
  }

  static const char* value(const ::signal_arm::gripper_joint_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19416ab4f14f2a07ULL;
  static const uint64_t static_value2 = 0x74e2bcefcc994034ULL;
};

template<class ContainerAllocator>
struct DataType< ::signal_arm::gripper_joint_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "signal_arm/gripper_joint_command";
  }

  static const char* value(const ::signal_arm::gripper_joint_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::signal_arm::gripper_joint_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float32 gripper_force\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::signal_arm::gripper_joint_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::signal_arm::gripper_joint_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gripper_force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gripper_joint_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::signal_arm::gripper_joint_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::signal_arm::gripper_joint_command_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gripper_force: ";
    Printer<float>::stream(s, indent + "  ", v.gripper_force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIGNAL_ARM_MESSAGE_GRIPPER_JOINT_COMMAND_H
