// Generated by gencpp from file signal_arm/status.msg
// DO NOT EDIT!


#ifndef SIGNAL_ARM_MESSAGE_STATUS_H
#define SIGNAL_ARM_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <signal_arm/motor_error.h>

namespace signal_arm
{
template <class ContainerAllocator>
struct status_
{
  typedef status_<ContainerAllocator> Type;

  status_()
    : name()
    , motor_errors()  {
    }
  status_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , motor_errors(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;

   typedef std::vector< ::signal_arm::motor_error_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::signal_arm::motor_error_<ContainerAllocator> >> _motor_errors_type;
  _motor_errors_type motor_errors;





  typedef boost::shared_ptr< ::signal_arm::status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::signal_arm::status_<ContainerAllocator> const> ConstPtr;

}; // struct status_

typedef ::signal_arm::status_<std::allocator<void> > status;

typedef boost::shared_ptr< ::signal_arm::status > statusPtr;
typedef boost::shared_ptr< ::signal_arm::status const> statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::signal_arm::status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::signal_arm::status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::signal_arm::status_<ContainerAllocator1> & lhs, const ::signal_arm::status_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.motor_errors == rhs.motor_errors;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::signal_arm::status_<ContainerAllocator1> & lhs, const ::signal_arm::status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace signal_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::signal_arm::status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::signal_arm::status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_arm::status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_arm::status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_arm::status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_arm::status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::signal_arm::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39b832c9a7480392677ff5c66f1fabe0";
  }

  static const char* value(const ::signal_arm::status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39b832c9a7480392ULL;
  static const uint64_t static_value2 = 0x677ff5c66f1fabe0ULL;
};

template<class ContainerAllocator>
struct DataType< ::signal_arm::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "signal_arm/status";
  }

  static const char* value(const ::signal_arm::status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::signal_arm::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name\n"
"motor_error[] motor_errors\n"
"================================================================================\n"
"MSG: signal_arm/motor_error\n"
"uint32 error_code\n"
"string[] error_description\n"
;
  }

  static const char* value(const ::signal_arm::status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::signal_arm::status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.motor_errors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::signal_arm::status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::signal_arm::status_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "motor_errors[]" << std::endl;
    for (size_t i = 0; i < v.motor_errors.size(); ++i)
    {
      s << indent << "  motor_errors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::signal_arm::motor_error_<ContainerAllocator> >::stream(s, indent + "    ", v.motor_errors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIGNAL_ARM_MESSAGE_STATUS_H
